### ISSUE TITLE
Enhancement: Ability to re-execute a migration plan and/or change target cluster

### ISSUE THREAD

**Issue by rgordill** [migtools/mig-ui#704]
There are some use cases where it is desirable to do a migration test to a destination cluster, check that everything is ok, and then delete everything and redo the migration to the same cluster or change the destination cluster (for example, from test to pro cluster).

That currently should be done by creating a new plan, but it can introduce some errors on the process.

**Comment by ibolton336** [comment]
Hi @rgordill  - Would the stage functionality help with this at all? The primary function of the stage feature is to test to see if a migration would be successful.

**Comment by rgordill** [comment]
Not exactly. AFAIK, if you somehow starts the application in the new cluster, the persistent data from the original copy will be modified, so there will not be any way to "complete" the migration (as now the delta is no longer valid).

Additionally, the second use case will require a cluster target change.

**Comment by rgordill** [comment]
No more needing this feature.
